#!/bin/bash

# Change directory to the folder where this script file lives
cd "$(dirname "$0")"

ENV=env
PORT=8000
export DJANGO_SUPERUSER_PASSWORD=w33d!

# create .env if it doesn't exist
[ ! -d "$ENV" ] && python3 -m venv $ENV

# activate virtual environment
. ${ENV}/bin/activate

# install dependencies
pip install .

time ./manage.py migrate
echo "Creating superuser - dev/dev"
./manage.py createsuperuser --noinput --username dev --email dev@example.com
./manage.py loaddata initial
