# Generated by Django 5.2.5 on 2025-08-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='dispensed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='finished',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='opened',
            field=models.DateField(blank=True, null=True),
        ),
    ]
