# Generated by Django 5.2 on 2025-08-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_container_dispensed_alter_container_finished_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='final',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurement',
            name='initial',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
