# Generated by Django 5.2 on 2025-08-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_measurement_final_measurement_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='initial_gross',
            field=models.FloatField(default=15.0),
            preserve_default=False,
        ),
    ]
