# Generated by Django 5.2 on 2025-08-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_container_initial_gross'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='thc',
            field=models.FloatField(default=22),
            preserve_default=False,
        ),
    ]
