# Generated by Django 5.2 on 2025-08-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_batch_thc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='thc',
        ),
        migrations.AddField(
            model_name='product',
            name='cbd',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='cbg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='thc',
            field=models.FloatField(default=0),
        ),
    ]
