# Generated by Django 5.2 on 2025-08-22 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_remove_batch_thc_product_cbd_product_cbg_product_thc'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=7),
            preserve_default=False,
        ),
    ]
