# Generated by Django 5.2 on 2025-08-22 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_container_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='cbc',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='cbv',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='thcv',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tracker.sponsor'),
        ),
    ]
