# Generated by Django 5.2 on 2025-08-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='monthly_target',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
