# Generated by Django 5.2 on 2025-08-25 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_patient_monthly_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('grams', models.FloatField(default=0)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('thc', models.FloatField(default=0)),
                ('cbd', models.FloatField(default=0)),
                ('cbg', models.FloatField(default=0)),
                ('cbv', models.FloatField(default=0)),
                ('cbc', models.FloatField(default=0)),
                ('thcv', models.FloatField(default=0)),
                ('containers', models.JSONField(default=list)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.patient')),
            ],
        ),
    ]
